Vagrant.configure("2") do |config|

  config.vm.define "gitserver" do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.network "private_network", type: "dhcp"
    node.vm.provision "shell", path: "bootstrap.sh"
    node.vm.hostname = "gitserver"
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "gitserver"
      vb.memory = "3072"
      vb.cpus = 2
    end
  end

end

